/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BookNFT {
  export type BookInfoStruct = {
    name: string;
    description: string;
    status: BigNumberish;
    condition: BigNumberish;
    createdAt: BigNumberish;
    imageBeforeHash: string;
    imageAfterHash: string;
  };

  export type BookInfoStructOutput = [
    name: string,
    description: string,
    status: bigint,
    condition: bigint,
    createdAt: bigint,
    imageBeforeHash: string,
    imageAfterHash: string
  ] & {
    name: string;
    description: string;
    status: bigint;
    condition: bigint;
    createdAt: bigint;
    imageBeforeHash: string;
    imageAfterHash: string;
  };
}

export interface BookNFTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approve"
      | "authorizedUpdaters"
      | "balanceOf"
      | "batchMintBooks"
      | "bookInfos"
      | "getApproved"
      | "getBookImage"
      | "getBookInfo"
      | "getBookStatus"
      | "getBooksByStatus"
      | "getCondition"
      | "getTotalBooks"
      | "isApprovedForAll"
      | "mintBook"
      | "mintBookWithCondition"
      | "mintBookWithImage"
      | "name"
      | "nextBookId"
      | "owner"
      | "ownerOf"
      | "renounceOwnership"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setAuthorizedUpdater"
      | "supportsInterface"
      | "symbol"
      | "tokenURI"
      | "transferFrom"
      | "transferOwnership"
      | "updateBookImage"
      | "updateBookInfo"
      | "updateBookStatus"
      | "updateCondition"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "BookImageUpdated"
      | "BookInfoUpdated"
      | "BookMinted"
      | "BookStatusUpdated"
      | "ConditionUpdated"
      | "OwnershipTransferred"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedUpdaters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchMintBooks",
    values: [string[], string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "bookInfos",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBookImage",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBookInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBookStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBooksByStatus",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCondition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalBooks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintBook",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintBookWithCondition",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintBookWithImage",
    values: [string, string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextBookId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedUpdater",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBookImage",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBookInfo",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBookStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCondition",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedUpdaters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchMintBooks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bookInfos", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBookImage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBookInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBookStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBooksByStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalBooks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintBook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintBookWithCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintBookWithImage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextBookId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedUpdater",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBookImage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBookInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBookStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCondition",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookImageUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    imageType: string,
    imageHash: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    imageType: string,
    imageHash: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    imageType: string;
    imageHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookInfoUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    name: string,
    description: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    name: string,
    description: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    name: string;
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookMintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    name: string,
    status: BigNumberish,
    condition: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    name: string,
    status: bigint,
    condition: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    name: string;
    status: bigint;
    condition: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookStatusUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConditionUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    oldCondition: BigNumberish,
    newCondition: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    oldCondition: bigint,
    newCondition: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    oldCondition: bigint;
    newCondition: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BookNFT extends BaseContract {
  connect(runner?: ContractRunner | null): BookNFT;
  waitForDeployment(): Promise<this>;

  interface: BookNFTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  authorizedUpdaters: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  batchMintBooks: TypedContractMethod<
    [names: string[], descriptions: string[], statuses: BigNumberish[]],
    [bigint[]],
    "nonpayable"
  >;

  bookInfos: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, string, string] & {
        name: string;
        description: string;
        status: bigint;
        condition: bigint;
        createdAt: bigint;
        imageBeforeHash: string;
        imageAfterHash: string;
      }
    ],
    "view"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getBookImage: TypedContractMethod<
    [tokenId: BigNumberish, imageType: string],
    [string],
    "view"
  >;

  getBookInfo: TypedContractMethod<
    [tokenId: BigNumberish],
    [BookNFT.BookInfoStructOutput],
    "view"
  >;

  getBookStatus: TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;

  getBooksByStatus: TypedContractMethod<
    [status: BigNumberish, offset: BigNumberish, limit: BigNumberish],
    [[bigint[], boolean] & { tokenIds: bigint[]; hasMore: boolean }],
    "view"
  >;

  getCondition: TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;

  getTotalBooks: TypedContractMethod<[], [bigint], "view">;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  mintBook: TypedContractMethod<
    [name: string, description: string, status: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  mintBookWithCondition: TypedContractMethod<
    [
      name: string,
      description: string,
      status: BigNumberish,
      condition: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  mintBookWithImage: TypedContractMethod<
    [
      name: string,
      description: string,
      status: BigNumberish,
      condition: BigNumberish,
      imageBeforeHash: string
    ],
    [bigint],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  nextBookId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setAuthorizedUpdater: TypedContractMethod<
    [updater: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateBookImage: TypedContractMethod<
    [tokenId: BigNumberish, imageType: string, imageHash: string],
    [void],
    "nonpayable"
  >;

  updateBookInfo: TypedContractMethod<
    [tokenId: BigNumberish, name: string, description: string],
    [void],
    "nonpayable"
  >;

  updateBookStatus: TypedContractMethod<
    [tokenId: BigNumberish, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateCondition: TypedContractMethod<
    [tokenId: BigNumberish, newCondition: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedUpdaters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchMintBooks"
  ): TypedContractMethod<
    [names: string[], descriptions: string[], statuses: BigNumberish[]],
    [bigint[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bookInfos"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, string, string] & {
        name: string;
        description: string;
        status: bigint;
        condition: bigint;
        createdAt: bigint;
        imageBeforeHash: string;
        imageAfterHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getBookImage"
  ): TypedContractMethod<
    [tokenId: BigNumberish, imageType: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBookInfo"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [BookNFT.BookInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBookStatus"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBooksByStatus"
  ): TypedContractMethod<
    [status: BigNumberish, offset: BigNumberish, limit: BigNumberish],
    [[bigint[], boolean] & { tokenIds: bigint[]; hasMore: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCondition"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalBooks"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintBook"
  ): TypedContractMethod<
    [name: string, description: string, status: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintBookWithCondition"
  ): TypedContractMethod<
    [
      name: string,
      description: string,
      status: BigNumberish,
      condition: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintBookWithImage"
  ): TypedContractMethod<
    [
      name: string,
      description: string,
      status: BigNumberish,
      condition: BigNumberish,
      imageBeforeHash: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextBookId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAuthorizedUpdater"
  ): TypedContractMethod<
    [updater: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateBookImage"
  ): TypedContractMethod<
    [tokenId: BigNumberish, imageType: string, imageHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateBookInfo"
  ): TypedContractMethod<
    [tokenId: BigNumberish, name: string, description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateBookStatus"
  ): TypedContractMethod<
    [tokenId: BigNumberish, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCondition"
  ): TypedContractMethod<
    [tokenId: BigNumberish, newCondition: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "BookImageUpdated"
  ): TypedContractEvent<
    BookImageUpdatedEvent.InputTuple,
    BookImageUpdatedEvent.OutputTuple,
    BookImageUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BookInfoUpdated"
  ): TypedContractEvent<
    BookInfoUpdatedEvent.InputTuple,
    BookInfoUpdatedEvent.OutputTuple,
    BookInfoUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BookMinted"
  ): TypedContractEvent<
    BookMintedEvent.InputTuple,
    BookMintedEvent.OutputTuple,
    BookMintedEvent.OutputObject
  >;
  getEvent(
    key: "BookStatusUpdated"
  ): TypedContractEvent<
    BookStatusUpdatedEvent.InputTuple,
    BookStatusUpdatedEvent.OutputTuple,
    BookStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ConditionUpdated"
  ): TypedContractEvent<
    ConditionUpdatedEvent.InputTuple,
    ConditionUpdatedEvent.OutputTuple,
    ConditionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "BookImageUpdated(uint256,string,string)": TypedContractEvent<
      BookImageUpdatedEvent.InputTuple,
      BookImageUpdatedEvent.OutputTuple,
      BookImageUpdatedEvent.OutputObject
    >;
    BookImageUpdated: TypedContractEvent<
      BookImageUpdatedEvent.InputTuple,
      BookImageUpdatedEvent.OutputTuple,
      BookImageUpdatedEvent.OutputObject
    >;

    "BookInfoUpdated(uint256,string,string)": TypedContractEvent<
      BookInfoUpdatedEvent.InputTuple,
      BookInfoUpdatedEvent.OutputTuple,
      BookInfoUpdatedEvent.OutputObject
    >;
    BookInfoUpdated: TypedContractEvent<
      BookInfoUpdatedEvent.InputTuple,
      BookInfoUpdatedEvent.OutputTuple,
      BookInfoUpdatedEvent.OutputObject
    >;

    "BookMinted(uint256,string,uint8,uint8)": TypedContractEvent<
      BookMintedEvent.InputTuple,
      BookMintedEvent.OutputTuple,
      BookMintedEvent.OutputObject
    >;
    BookMinted: TypedContractEvent<
      BookMintedEvent.InputTuple,
      BookMintedEvent.OutputTuple,
      BookMintedEvent.OutputObject
    >;

    "BookStatusUpdated(uint256,uint8,uint8)": TypedContractEvent<
      BookStatusUpdatedEvent.InputTuple,
      BookStatusUpdatedEvent.OutputTuple,
      BookStatusUpdatedEvent.OutputObject
    >;
    BookStatusUpdated: TypedContractEvent<
      BookStatusUpdatedEvent.InputTuple,
      BookStatusUpdatedEvent.OutputTuple,
      BookStatusUpdatedEvent.OutputObject
    >;

    "ConditionUpdated(uint256,uint8,uint8)": TypedContractEvent<
      ConditionUpdatedEvent.InputTuple,
      ConditionUpdatedEvent.OutputTuple,
      ConditionUpdatedEvent.OutputObject
    >;
    ConditionUpdated: TypedContractEvent<
      ConditionUpdatedEvent.InputTuple,
      ConditionUpdatedEvent.OutputTuple,
      ConditionUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
