/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EscrowVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "depositOf"
      | "getBalance"
      | "getDeposit"
      | "libraryCore"
      | "lock"
      | "owner"
      | "release"
      | "setCore"
      | "withdrawAllPenalty"
      | "withdrawPenalty"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CoreSet" | "Locked" | "Released"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "depositOf",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDeposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "libraryCore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lock",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAllPenalty",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPenalty",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "depositOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "libraryCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setCore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAllPenalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPenalty",
    data: BytesLike
  ): Result;
}

export namespace CoreSetEvent {
  export type InputTuple = [core: AddressLike];
  export type OutputTuple = [core: string];
  export interface OutputObject {
    core: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LockedEvent {
  export type InputTuple = [
    user: AddressLike,
    bookId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, bookId: bigint, amount: bigint];
  export interface OutputObject {
    user: string;
    bookId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleasedEvent {
  export type InputTuple = [
    to: AddressLike,
    bookId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [to: string, bookId: bigint, amount: bigint];
  export interface OutputObject {
    to: string;
    bookId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowVault extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowVault;
  waitForDeployment(): Promise<this>;

  interface: EscrowVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositOf: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getDeposit: TypedContractMethod<
    [user: AddressLike, bookId: BigNumberish],
    [bigint],
    "view"
  >;

  libraryCore: TypedContractMethod<[], [string], "view">;

  lock: TypedContractMethod<
    [user: AddressLike, bookId: BigNumberish, amt: BigNumberish],
    [void],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  release: TypedContractMethod<
    [to: AddressLike, bookId: BigNumberish, amt: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCore: TypedContractMethod<[_core: AddressLike], [void], "nonpayable">;

  withdrawAllPenalty: TypedContractMethod<[], [void], "nonpayable">;

  withdrawPenalty: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositOf"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDeposit"
  ): TypedContractMethod<
    [user: AddressLike, bookId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "libraryCore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lock"
  ): TypedContractMethod<
    [user: AddressLike, bookId: BigNumberish, amt: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<
    [to: AddressLike, bookId: BigNumberish, amt: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCore"
  ): TypedContractMethod<[_core: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawAllPenalty"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPenalty"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "CoreSet"
  ): TypedContractEvent<
    CoreSetEvent.InputTuple,
    CoreSetEvent.OutputTuple,
    CoreSetEvent.OutputObject
  >;
  getEvent(
    key: "Locked"
  ): TypedContractEvent<
    LockedEvent.InputTuple,
    LockedEvent.OutputTuple,
    LockedEvent.OutputObject
  >;
  getEvent(
    key: "Released"
  ): TypedContractEvent<
    ReleasedEvent.InputTuple,
    ReleasedEvent.OutputTuple,
    ReleasedEvent.OutputObject
  >;

  filters: {
    "CoreSet(address)": TypedContractEvent<
      CoreSetEvent.InputTuple,
      CoreSetEvent.OutputTuple,
      CoreSetEvent.OutputObject
    >;
    CoreSet: TypedContractEvent<
      CoreSetEvent.InputTuple,
      CoreSetEvent.OutputTuple,
      CoreSetEvent.OutputObject
    >;

    "Locked(address,uint256,uint256)": TypedContractEvent<
      LockedEvent.InputTuple,
      LockedEvent.OutputTuple,
      LockedEvent.OutputObject
    >;
    Locked: TypedContractEvent<
      LockedEvent.InputTuple,
      LockedEvent.OutputTuple,
      LockedEvent.OutputObject
    >;

    "Released(address,uint256,uint256)": TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
    Released: TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
  };
}
