/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace LibraryCoreV3 {
  export type LoanInfoStruct = {
    borrower: AddressLike;
    borrowedAt: BigNumberish;
    dueDate: BigNumberish;
    deposit: BigNumberish;
    isReturned: boolean;
    statusAtLoan: BigNumberish;
    statusAtReturn: BigNumberish;
    returnedAt: BigNumberish;
    latePenalty: BigNumberish;
    damagePenalty: BigNumberish;
  };

  export type LoanInfoStructOutput = [
    borrower: string,
    borrowedAt: bigint,
    dueDate: bigint,
    deposit: bigint,
    isReturned: boolean,
    statusAtLoan: bigint,
    statusAtReturn: bigint,
    returnedAt: bigint,
    latePenalty: bigint,
    damagePenalty: bigint
  ] & {
    borrower: string;
    borrowedAt: bigint;
    dueDate: bigint;
    deposit: bigint;
    isReturned: boolean;
    statusAtLoan: bigint;
    statusAtReturn: bigint;
    returnedAt: bigint;
    latePenalty: bigint;
    damagePenalty: bigint;
  };
}

export interface LibraryCoreV3Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_DEPOSIT"
      | "GOOD_REPUTATION_THRESHOLD"
      | "LOAN_PERIOD"
      | "PENALTY_DAMAGE"
      | "PENALTY_LATE_PER_DAY"
      | "approveReturn"
      | "bookNFT"
      | "bookReservations"
      | "borrowBook"
      | "calculateCurrentPenalty"
      | "escrowVault"
      | "extendLoan"
      | "getBookReservations"
      | "getLoanInfo"
      | "getPendingReturnRequests"
      | "getUserCurrentLoans"
      | "getUserLoanHistory"
      | "hasReserved"
      | "isBookBorrowed"
      | "loanInfos"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "requestReturn"
      | "reserveBook"
      | "returnBook"
      | "returnRequestCounter"
      | "returnRequests"
      | "roleManager"
      | "totalPenaltyCollected"
      | "transferOwnership"
      | "unpause"
      | "userCart"
      | "userCurrentLoans"
      | "userLoanHistory"
      | "userProfile"
      | "withdrawAllPenalty"
      | "withdrawPenalty"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BookBorrowed"
      | "BookReserved"
      | "BookReturned"
      | "DeprecatedFunctionUsed"
      | "LoanExtended"
      | "OwnershipTransferred"
      | "Paused"
      | "ReturnApproved"
      | "ReturnRequested"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_DEPOSIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOOD_REPUTATION_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOAN_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PENALTY_DAMAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PENALTY_LATE_PER_DAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveReturn",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "bookNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bookReservations",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowBook",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateCurrentPenalty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "extendLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBookReservations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingReturnRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCurrentLoans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserLoanHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReserved",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBookBorrowed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "loanInfos",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestReturn",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reserveBook",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "returnBook",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "returnRequestCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "returnRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "roleManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPenaltyCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "userCart", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userCurrentLoans",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userLoanHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAllPenalty",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPenalty",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_DEPOSIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOOD_REPUTATION_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOAN_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PENALTY_DAMAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PENALTY_LATE_PER_DAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bookNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bookReservations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrowBook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateCurrentPenalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "extendLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBookReservations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLoanInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingReturnRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCurrentLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserLoanHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReserved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBookBorrowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loanInfos", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveBook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "returnBook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "returnRequestCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "returnRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPenaltyCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userCart", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userCurrentLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userLoanHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAllPenalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPenalty",
    data: BytesLike
  ): Result;
}

export namespace BookBorrowedEvent {
  export type InputTuple = [
    borrower: AddressLike,
    bookId: BigNumberish,
    deposit: BigNumberish,
    dueDate: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    borrower: string,
    bookId: bigint,
    deposit: bigint,
    dueDate: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    borrower: string;
    bookId: bigint;
    deposit: bigint;
    dueDate: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookReservedEvent {
  export type InputTuple = [
    bookId: BigNumberish,
    user: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [bookId: bigint, user: string, timestamp: bigint];
  export interface OutputObject {
    bookId: bigint;
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookReturnedEvent {
  export type InputTuple = [
    borrower: AddressLike,
    bookId: BigNumberish,
    penalty: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    borrower: string,
    bookId: bigint,
    penalty: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    borrower: string;
    bookId: bigint;
    penalty: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeprecatedFunctionUsedEvent {
  export type InputTuple = [
    caller: AddressLike,
    functionName: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    caller: string,
    functionName: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    caller: string;
    functionName: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanExtendedEvent {
  export type InputTuple = [
    bookId: BigNumberish,
    borrower: AddressLike,
    newDueDate: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    bookId: bigint,
    borrower: string,
    newDueDate: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    bookId: bigint;
    borrower: string;
    newDueDate: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReturnApprovedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    approver: AddressLike,
    finalCondition: BigNumberish,
    penalty: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    approver: string,
    finalCondition: bigint,
    penalty: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    approver: string;
    finalCondition: bigint;
    penalty: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReturnRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    borrower: AddressLike,
    bookId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    borrower: string,
    bookId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    borrower: string;
    bookId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LibraryCoreV3 extends BaseContract {
  connect(runner?: ContractRunner | null): LibraryCoreV3;
  waitForDeployment(): Promise<this>;

  interface: LibraryCoreV3Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_DEPOSIT: TypedContractMethod<[], [bigint], "view">;

  GOOD_REPUTATION_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  LOAN_PERIOD: TypedContractMethod<[], [bigint], "view">;

  PENALTY_DAMAGE: TypedContractMethod<[], [bigint], "view">;

  PENALTY_LATE_PER_DAY: TypedContractMethod<[], [bigint], "view">;

  approveReturn: TypedContractMethod<
    [requestId: BigNumberish, finalCondition: BigNumberish],
    [void],
    "nonpayable"
  >;

  bookNFT: TypedContractMethod<[], [string], "view">;

  bookReservations: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  borrowBook: TypedContractMethod<[bookId: BigNumberish], [void], "payable">;

  calculateCurrentPenalty: TypedContractMethod<
    [bookId: BigNumberish],
    [bigint],
    "view"
  >;

  escrowVault: TypedContractMethod<[], [string], "view">;

  extendLoan: TypedContractMethod<[bookId: BigNumberish], [void], "payable">;

  getBookReservations: TypedContractMethod<
    [bookId: BigNumberish],
    [string[]],
    "view"
  >;

  getLoanInfo: TypedContractMethod<
    [bookId: BigNumberish],
    [LibraryCoreV3.LoanInfoStructOutput],
    "view"
  >;

  getPendingReturnRequests: TypedContractMethod<[], [bigint[]], "view">;

  getUserCurrentLoans: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  getUserLoanHistory: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  hasReserved: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isBookBorrowed: TypedContractMethod<
    [bookId: BigNumberish],
    [boolean],
    "view"
  >;

  loanInfos: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        borrower: string;
        borrowedAt: bigint;
        dueDate: bigint;
        deposit: bigint;
        isReturned: boolean;
        statusAtLoan: bigint;
        statusAtReturn: bigint;
        returnedAt: bigint;
        latePenalty: bigint;
        damagePenalty: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestReturn: TypedContractMethod<
    [bookId: BigNumberish, proposedCondition: BigNumberish],
    [void],
    "nonpayable"
  >;

  reserveBook: TypedContractMethod<
    [bookId: BigNumberish],
    [void],
    "nonpayable"
  >;

  returnBook: TypedContractMethod<
    [bookId: BigNumberish, returnStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  returnRequestCounter: TypedContractMethod<[], [bigint], "view">;

  returnRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean, boolean, string, bigint] & {
        borrower: string;
        bookId: bigint;
        requestedAt: bigint;
        proposedCondition: bigint;
        isPending: boolean;
        isApproved: boolean;
        approvedBy: string;
        approvedAt: bigint;
      }
    ],
    "view"
  >;

  roleManager: TypedContractMethod<[], [string], "view">;

  totalPenaltyCollected: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userCart: TypedContractMethod<[], [string], "view">;

  userCurrentLoans: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userLoanHistory: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userProfile: TypedContractMethod<[], [string], "view">;

  withdrawAllPenalty: TypedContractMethod<[], [void], "nonpayable">;

  withdrawPenalty: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_DEPOSIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GOOD_REPUTATION_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOAN_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PENALTY_DAMAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PENALTY_LATE_PER_DAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveReturn"
  ): TypedContractMethod<
    [requestId: BigNumberish, finalCondition: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bookNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bookReservations"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "borrowBook"
  ): TypedContractMethod<[bookId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "calculateCurrentPenalty"
  ): TypedContractMethod<[bookId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrowVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "extendLoan"
  ): TypedContractMethod<[bookId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getBookReservations"
  ): TypedContractMethod<[bookId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getLoanInfo"
  ): TypedContractMethod<
    [bookId: BigNumberish],
    [LibraryCoreV3.LoanInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingReturnRequests"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserCurrentLoans"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserLoanHistory"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hasReserved"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isBookBorrowed"
  ): TypedContractMethod<[bookId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "loanInfos"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        borrower: string;
        borrowedAt: bigint;
        dueDate: bigint;
        deposit: bigint;
        isReturned: boolean;
        statusAtLoan: bigint;
        statusAtReturn: bigint;
        returnedAt: bigint;
        latePenalty: bigint;
        damagePenalty: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestReturn"
  ): TypedContractMethod<
    [bookId: BigNumberish, proposedCondition: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reserveBook"
  ): TypedContractMethod<[bookId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "returnBook"
  ): TypedContractMethod<
    [bookId: BigNumberish, returnStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "returnRequestCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "returnRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean, boolean, string, bigint] & {
        borrower: string;
        bookId: bigint;
        requestedAt: bigint;
        proposedCondition: bigint;
        isPending: boolean;
        isApproved: boolean;
        approvedBy: string;
        approvedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "roleManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalPenaltyCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userCart"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userCurrentLoans"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userLoanHistory"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userProfile"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawAllPenalty"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPenalty"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BookBorrowed"
  ): TypedContractEvent<
    BookBorrowedEvent.InputTuple,
    BookBorrowedEvent.OutputTuple,
    BookBorrowedEvent.OutputObject
  >;
  getEvent(
    key: "BookReserved"
  ): TypedContractEvent<
    BookReservedEvent.InputTuple,
    BookReservedEvent.OutputTuple,
    BookReservedEvent.OutputObject
  >;
  getEvent(
    key: "BookReturned"
  ): TypedContractEvent<
    BookReturnedEvent.InputTuple,
    BookReturnedEvent.OutputTuple,
    BookReturnedEvent.OutputObject
  >;
  getEvent(
    key: "DeprecatedFunctionUsed"
  ): TypedContractEvent<
    DeprecatedFunctionUsedEvent.InputTuple,
    DeprecatedFunctionUsedEvent.OutputTuple,
    DeprecatedFunctionUsedEvent.OutputObject
  >;
  getEvent(
    key: "LoanExtended"
  ): TypedContractEvent<
    LoanExtendedEvent.InputTuple,
    LoanExtendedEvent.OutputTuple,
    LoanExtendedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ReturnApproved"
  ): TypedContractEvent<
    ReturnApprovedEvent.InputTuple,
    ReturnApprovedEvent.OutputTuple,
    ReturnApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ReturnRequested"
  ): TypedContractEvent<
    ReturnRequestedEvent.InputTuple,
    ReturnRequestedEvent.OutputTuple,
    ReturnRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BookBorrowed(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      BookBorrowedEvent.InputTuple,
      BookBorrowedEvent.OutputTuple,
      BookBorrowedEvent.OutputObject
    >;
    BookBorrowed: TypedContractEvent<
      BookBorrowedEvent.InputTuple,
      BookBorrowedEvent.OutputTuple,
      BookBorrowedEvent.OutputObject
    >;

    "BookReserved(uint256,address,uint256)": TypedContractEvent<
      BookReservedEvent.InputTuple,
      BookReservedEvent.OutputTuple,
      BookReservedEvent.OutputObject
    >;
    BookReserved: TypedContractEvent<
      BookReservedEvent.InputTuple,
      BookReservedEvent.OutputTuple,
      BookReservedEvent.OutputObject
    >;

    "BookReturned(address,uint256,uint256,uint256)": TypedContractEvent<
      BookReturnedEvent.InputTuple,
      BookReturnedEvent.OutputTuple,
      BookReturnedEvent.OutputObject
    >;
    BookReturned: TypedContractEvent<
      BookReturnedEvent.InputTuple,
      BookReturnedEvent.OutputTuple,
      BookReturnedEvent.OutputObject
    >;

    "DeprecatedFunctionUsed(address,string,uint256)": TypedContractEvent<
      DeprecatedFunctionUsedEvent.InputTuple,
      DeprecatedFunctionUsedEvent.OutputTuple,
      DeprecatedFunctionUsedEvent.OutputObject
    >;
    DeprecatedFunctionUsed: TypedContractEvent<
      DeprecatedFunctionUsedEvent.InputTuple,
      DeprecatedFunctionUsedEvent.OutputTuple,
      DeprecatedFunctionUsedEvent.OutputObject
    >;

    "LoanExtended(uint256,address,uint256,uint256)": TypedContractEvent<
      LoanExtendedEvent.InputTuple,
      LoanExtendedEvent.OutputTuple,
      LoanExtendedEvent.OutputObject
    >;
    LoanExtended: TypedContractEvent<
      LoanExtendedEvent.InputTuple,
      LoanExtendedEvent.OutputTuple,
      LoanExtendedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ReturnApproved(uint256,address,uint8,uint256,uint256)": TypedContractEvent<
      ReturnApprovedEvent.InputTuple,
      ReturnApprovedEvent.OutputTuple,
      ReturnApprovedEvent.OutputObject
    >;
    ReturnApproved: TypedContractEvent<
      ReturnApprovedEvent.InputTuple,
      ReturnApprovedEvent.OutputTuple,
      ReturnApprovedEvent.OutputObject
    >;

    "ReturnRequested(uint256,address,uint256,uint256)": TypedContractEvent<
      ReturnRequestedEvent.InputTuple,
      ReturnRequestedEvent.OutputTuple,
      ReturnRequestedEvent.OutputObject
    >;
    ReturnRequested: TypedContractEvent<
      ReturnRequestedEvent.InputTuple,
      ReturnRequestedEvent.OutputTuple,
      ReturnRequestedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
