/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace LibraryCoreV2 {
  export type LoanInfoStruct = {
    borrower: AddressLike;
    borrowedAt: BigNumberish;
    dueDate: BigNumberish;
    deposit: BigNumberish;
    isReturned: boolean;
    statusAtLoan: BigNumberish;
    statusAtReturn: BigNumberish;
    returnedAt: BigNumberish;
    penaltyPaid: BigNumberish;
  };

  export type LoanInfoStructOutput = [
    borrower: string,
    borrowedAt: bigint,
    dueDate: bigint,
    deposit: bigint,
    isReturned: boolean,
    statusAtLoan: bigint,
    statusAtReturn: bigint,
    returnedAt: bigint,
    penaltyPaid: bigint
  ] & {
    borrower: string;
    borrowedAt: bigint;
    dueDate: bigint;
    deposit: bigint;
    isReturned: boolean;
    statusAtLoan: bigint;
    statusAtReturn: bigint;
    returnedAt: bigint;
    penaltyPaid: bigint;
  };
}

export interface LibraryCoreV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_DEPOSIT"
      | "GOOD_REPUTATION_THRESHOLD"
      | "LOAN_PERIOD"
      | "PENALTY_DAMAGE"
      | "PENALTY_LATE"
      | "bookNFT"
      | "bookReservations"
      | "borrowBook"
      | "getBookReservations"
      | "getLoanInfo"
      | "getReputation"
      | "getUserCurrentLoans"
      | "getUserLoanHistory"
      | "hasReserved"
      | "loanInfos"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "reserveBook"
      | "returnBook"
      | "totalPenaltyCollected"
      | "transferOwnership"
      | "unpause"
      | "userCurrentLoans"
      | "userLoanHistory"
      | "userProfile"
      | "userReputation"
      | "withdrawAllPenalty"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BookBorrowed"
      | "BookReserved"
      | "BookReturned"
      | "OwnershipTransferred"
      | "Paused"
      | "ReputationUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_DEPOSIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOOD_REPUTATION_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOAN_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PENALTY_DAMAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PENALTY_LATE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bookNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bookReservations",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowBook",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBookReservations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCurrentLoans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserLoanHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReserved",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "loanInfos",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveBook",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "returnBook",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPenaltyCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userCurrentLoans",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userLoanHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAllPenalty",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_DEPOSIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOOD_REPUTATION_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOAN_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PENALTY_DAMAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PENALTY_LATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bookNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bookReservations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrowBook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBookReservations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLoanInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCurrentLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserLoanHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReserved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loanInfos", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveBook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "returnBook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalPenaltyCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userCurrentLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userLoanHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAllPenalty",
    data: BytesLike
  ): Result;
}

export namespace BookBorrowedEvent {
  export type InputTuple = [
    bookId: BigNumberish,
    borrower: AddressLike,
    deposit: BigNumberish,
    dueDate: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    bookId: bigint,
    borrower: string,
    deposit: bigint,
    dueDate: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    bookId: bigint;
    borrower: string;
    deposit: bigint;
    dueDate: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookReservedEvent {
  export type InputTuple = [
    bookId: BigNumberish,
    user: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [bookId: bigint, user: string, timestamp: bigint];
  export interface OutputObject {
    bookId: bigint;
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookReturnedEvent {
  export type InputTuple = [
    bookId: BigNumberish,
    borrower: AddressLike,
    returnStatus: BigNumberish,
    penaltyPaid: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    bookId: bigint,
    borrower: string,
    returnStatus: bigint,
    penaltyPaid: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    bookId: bigint;
    borrower: string;
    returnStatus: bigint;
    penaltyPaid: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    oldReputation: BigNumberish,
    newReputation: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    oldReputation: bigint,
    newReputation: bigint
  ];
  export interface OutputObject {
    user: string;
    oldReputation: bigint;
    newReputation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LibraryCoreV2 extends BaseContract {
  connect(runner?: ContractRunner | null): LibraryCoreV2;
  waitForDeployment(): Promise<this>;

  interface: LibraryCoreV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_DEPOSIT: TypedContractMethod<[], [bigint], "view">;

  GOOD_REPUTATION_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  LOAN_PERIOD: TypedContractMethod<[], [bigint], "view">;

  PENALTY_DAMAGE: TypedContractMethod<[], [bigint], "view">;

  PENALTY_LATE: TypedContractMethod<[], [bigint], "view">;

  bookNFT: TypedContractMethod<[], [string], "view">;

  bookReservations: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  borrowBook: TypedContractMethod<[bookId: BigNumberish], [void], "payable">;

  getBookReservations: TypedContractMethod<
    [bookId: BigNumberish],
    [string[]],
    "view"
  >;

  getLoanInfo: TypedContractMethod<
    [bookId: BigNumberish],
    [LibraryCoreV2.LoanInfoStructOutput],
    "view"
  >;

  getReputation: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUserCurrentLoans: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  getUserLoanHistory: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  hasReserved: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  loanInfos: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        borrower: string;
        borrowedAt: bigint;
        dueDate: bigint;
        deposit: bigint;
        isReturned: boolean;
        statusAtLoan: bigint;
        statusAtReturn: bigint;
        returnedAt: bigint;
        penaltyPaid: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reserveBook: TypedContractMethod<
    [bookId: BigNumberish],
    [void],
    "nonpayable"
  >;

  returnBook: TypedContractMethod<
    [bookId: BigNumberish, returnStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalPenaltyCollected: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userCurrentLoans: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userLoanHistory: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userProfile: TypedContractMethod<[], [string], "view">;

  userReputation: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdrawAllPenalty: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_DEPOSIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GOOD_REPUTATION_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOAN_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PENALTY_DAMAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PENALTY_LATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bookNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bookReservations"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "borrowBook"
  ): TypedContractMethod<[bookId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getBookReservations"
  ): TypedContractMethod<[bookId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getLoanInfo"
  ): TypedContractMethod<
    [bookId: BigNumberish],
    [LibraryCoreV2.LoanInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserCurrentLoans"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserLoanHistory"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hasReserved"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "loanInfos"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        borrower: string;
        borrowedAt: bigint;
        dueDate: bigint;
        deposit: bigint;
        isReturned: boolean;
        statusAtLoan: bigint;
        statusAtReturn: bigint;
        returnedAt: bigint;
        penaltyPaid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reserveBook"
  ): TypedContractMethod<[bookId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "returnBook"
  ): TypedContractMethod<
    [bookId: BigNumberish, returnStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalPenaltyCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userCurrentLoans"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userLoanHistory"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userProfile"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userReputation"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawAllPenalty"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BookBorrowed"
  ): TypedContractEvent<
    BookBorrowedEvent.InputTuple,
    BookBorrowedEvent.OutputTuple,
    BookBorrowedEvent.OutputObject
  >;
  getEvent(
    key: "BookReserved"
  ): TypedContractEvent<
    BookReservedEvent.InputTuple,
    BookReservedEvent.OutputTuple,
    BookReservedEvent.OutputObject
  >;
  getEvent(
    key: "BookReturned"
  ): TypedContractEvent<
    BookReturnedEvent.InputTuple,
    BookReturnedEvent.OutputTuple,
    BookReturnedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BookBorrowed(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      BookBorrowedEvent.InputTuple,
      BookBorrowedEvent.OutputTuple,
      BookBorrowedEvent.OutputObject
    >;
    BookBorrowed: TypedContractEvent<
      BookBorrowedEvent.InputTuple,
      BookBorrowedEvent.OutputTuple,
      BookBorrowedEvent.OutputObject
    >;

    "BookReserved(uint256,address,uint256)": TypedContractEvent<
      BookReservedEvent.InputTuple,
      BookReservedEvent.OutputTuple,
      BookReservedEvent.OutputObject
    >;
    BookReserved: TypedContractEvent<
      BookReservedEvent.InputTuple,
      BookReservedEvent.OutputTuple,
      BookReservedEvent.OutputObject
    >;

    "BookReturned(uint256,address,uint8,uint256,uint256)": TypedContractEvent<
      BookReturnedEvent.InputTuple,
      BookReturnedEvent.OutputTuple,
      BookReturnedEvent.OutputObject
    >;
    BookReturned: TypedContractEvent<
      BookReturnedEvent.InputTuple,
      BookReturnedEvent.OutputTuple,
      BookReturnedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ReputationUpdated(address,int256,int256)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
