/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace LibraryCore {
  export type LoanInfoStruct = {
    borrower: AddressLike;
    borrowedAt: BigNumberish;
    dueDate: BigNumberish;
    deposit: BigNumberish;
    isReturned: boolean;
    statusAtLoan: BigNumberish;
    statusAtReturn: BigNumberish;
    latePenalty: BigNumberish;
    damagePenalty: BigNumberish;
    overdue: boolean;
    damaged: boolean;
    imageBeforeHash: string;
    imageAfterHash: string;
  };

  export type LoanInfoStructOutput = [
    borrower: string,
    borrowedAt: bigint,
    dueDate: bigint,
    deposit: bigint,
    isReturned: boolean,
    statusAtLoan: bigint,
    statusAtReturn: bigint,
    latePenalty: bigint,
    damagePenalty: bigint,
    overdue: boolean,
    damaged: boolean,
    imageBeforeHash: string,
    imageAfterHash: string
  ] & {
    borrower: string;
    borrowedAt: bigint;
    dueDate: bigint;
    deposit: bigint;
    isReturned: boolean;
    statusAtLoan: bigint;
    statusAtReturn: bigint;
    latePenalty: bigint;
    damagePenalty: bigint;
    overdue: boolean;
    damaged: boolean;
    imageBeforeHash: string;
    imageAfterHash: string;
  };
}

export interface LibraryCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_DEPOSIT"
      | "GOOD_REPUTATION_THRESHOLD"
      | "LOAN_PERIOD"
      | "PENALTY_DAMAGE"
      | "PENALTY_LATE"
      | "bookNFT"
      | "bookReservations"
      | "borrowBook"
      | "calculatePenalty"
      | "extendLoan"
      | "getBookReservations"
      | "getLoanInfo"
      | "getReputation"
      | "hasReserved"
      | "isBookBorrowed"
      | "loanInfos"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "reserveBook"
      | "returnBook"
      | "returnBookWithImage"
      | "totalPenaltyCollected"
      | "transferOwnership"
      | "unpause"
      | "updateBookInfo"
      | "userReputation"
      | "withdrawAllPenalty"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BookAvailableForReservation"
      | "BookBorrowed"
      | "BookInfoUpdated"
      | "BookReserved"
      | "BookReturned"
      | "LoanExtended"
      | "OwnershipTransferred"
      | "Paused"
      | "PenaltyWithdrawn"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_DEPOSIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOOD_REPUTATION_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOAN_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PENALTY_DAMAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PENALTY_LATE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bookNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bookReservations",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowBook",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePenalty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "extendLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBookReservations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReserved",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBookBorrowed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "loanInfos",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveBook",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "returnBook",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "returnBookWithImage",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPenaltyCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateBookInfo",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "userReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAllPenalty",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_DEPOSIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOOD_REPUTATION_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOAN_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PENALTY_DAMAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PENALTY_LATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bookNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bookReservations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrowBook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculatePenalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "extendLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBookReservations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLoanInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReserved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBookBorrowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loanInfos", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveBook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "returnBook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "returnBookWithImage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPenaltyCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateBookInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAllPenalty",
    data: BytesLike
  ): Result;
}

export namespace BookAvailableForReservationEvent {
  export type InputTuple = [tokenId: BigNumberish, reserver: AddressLike];
  export type OutputTuple = [tokenId: bigint, reserver: string];
  export interface OutputObject {
    tokenId: bigint;
    reserver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookBorrowedEvent {
  export type InputTuple = [
    borrower: AddressLike,
    tokenId: BigNumberish,
    deposit: BigNumberish,
    dueDate: BigNumberish
  ];
  export type OutputTuple = [
    borrower: string,
    tokenId: bigint,
    deposit: bigint,
    dueDate: bigint
  ];
  export interface OutputObject {
    borrower: string;
    tokenId: bigint;
    deposit: bigint;
    dueDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookInfoUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    name: string,
    description: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    name: string,
    description: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    name: string;
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookReservedEvent {
  export type InputTuple = [tokenId: BigNumberish, reserver: AddressLike];
  export type OutputTuple = [tokenId: bigint, reserver: string];
  export interface OutputObject {
    tokenId: bigint;
    reserver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookReturnedEvent {
  export type InputTuple = [
    borrower: AddressLike,
    tokenId: BigNumberish,
    penalty: BigNumberish,
    reputationDelta: BigNumberish,
    imageAfterHash: string
  ];
  export type OutputTuple = [
    borrower: string,
    tokenId: bigint,
    penalty: bigint,
    reputationDelta: bigint,
    imageAfterHash: string
  ];
  export interface OutputObject {
    borrower: string;
    tokenId: bigint;
    penalty: bigint;
    reputationDelta: bigint;
    imageAfterHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanExtendedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    borrower: AddressLike,
    newDueDate: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    borrower: string,
    newDueDate: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    borrower: string;
    newDueDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PenaltyWithdrawnEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LibraryCore extends BaseContract {
  connect(runner?: ContractRunner | null): LibraryCore;
  waitForDeployment(): Promise<this>;

  interface: LibraryCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_DEPOSIT: TypedContractMethod<[], [bigint], "view">;

  GOOD_REPUTATION_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  LOAN_PERIOD: TypedContractMethod<[], [bigint], "view">;

  PENALTY_DAMAGE: TypedContractMethod<[], [bigint], "view">;

  PENALTY_LATE: TypedContractMethod<[], [bigint], "view">;

  bookNFT: TypedContractMethod<[], [string], "view">;

  bookReservations: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  borrowBook: TypedContractMethod<[tokenId: BigNumberish], [void], "payable">;

  calculatePenalty: TypedContractMethod<
    [tokenId: BigNumberish],
    [[bigint, boolean] & { penalty: bigint; isOverdue: boolean }],
    "view"
  >;

  extendLoan: TypedContractMethod<[tokenId: BigNumberish], [void], "payable">;

  getBookReservations: TypedContractMethod<
    [tokenId: BigNumberish],
    [string[]],
    "view"
  >;

  getLoanInfo: TypedContractMethod<
    [tokenId: BigNumberish],
    [LibraryCore.LoanInfoStructOutput],
    "view"
  >;

  getReputation: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  hasReserved: TypedContractMethod<
    [tokenId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  isBookBorrowed: TypedContractMethod<
    [tokenId: BigNumberish],
    [boolean],
    "view"
  >;

  loanInfos: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        string
      ] & {
        borrower: string;
        borrowedAt: bigint;
        dueDate: bigint;
        deposit: bigint;
        isReturned: boolean;
        statusAtLoan: bigint;
        statusAtReturn: bigint;
        latePenalty: bigint;
        damagePenalty: bigint;
        overdue: boolean;
        damaged: boolean;
        imageBeforeHash: string;
        imageAfterHash: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reserveBook: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  returnBook: TypedContractMethod<
    [tokenId: BigNumberish, afterStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  returnBookWithImage: TypedContractMethod<
    [tokenId: BigNumberish, afterStatus: BigNumberish, imageAfterHash: string],
    [void],
    "nonpayable"
  >;

  totalPenaltyCollected: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateBookInfo: TypedContractMethod<
    [tokenId: BigNumberish, name: string, description: string],
    [void],
    "nonpayable"
  >;

  userReputation: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdrawAllPenalty: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_DEPOSIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GOOD_REPUTATION_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOAN_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PENALTY_DAMAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PENALTY_LATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bookNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bookReservations"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "borrowBook"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "calculatePenalty"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [[bigint, boolean] & { penalty: bigint; isOverdue: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "extendLoan"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getBookReservations"
  ): TypedContractMethod<[tokenId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getLoanInfo"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [LibraryCore.LoanInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasReserved"
  ): TypedContractMethod<
    [tokenId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isBookBorrowed"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "loanInfos"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        string
      ] & {
        borrower: string;
        borrowedAt: bigint;
        dueDate: bigint;
        deposit: bigint;
        isReturned: boolean;
        statusAtLoan: bigint;
        statusAtReturn: bigint;
        latePenalty: bigint;
        damagePenalty: bigint;
        overdue: boolean;
        damaged: boolean;
        imageBeforeHash: string;
        imageAfterHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reserveBook"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "returnBook"
  ): TypedContractMethod<
    [tokenId: BigNumberish, afterStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "returnBookWithImage"
  ): TypedContractMethod<
    [tokenId: BigNumberish, afterStatus: BigNumberish, imageAfterHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalPenaltyCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateBookInfo"
  ): TypedContractMethod<
    [tokenId: BigNumberish, name: string, description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userReputation"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawAllPenalty"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BookAvailableForReservation"
  ): TypedContractEvent<
    BookAvailableForReservationEvent.InputTuple,
    BookAvailableForReservationEvent.OutputTuple,
    BookAvailableForReservationEvent.OutputObject
  >;
  getEvent(
    key: "BookBorrowed"
  ): TypedContractEvent<
    BookBorrowedEvent.InputTuple,
    BookBorrowedEvent.OutputTuple,
    BookBorrowedEvent.OutputObject
  >;
  getEvent(
    key: "BookInfoUpdated"
  ): TypedContractEvent<
    BookInfoUpdatedEvent.InputTuple,
    BookInfoUpdatedEvent.OutputTuple,
    BookInfoUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BookReserved"
  ): TypedContractEvent<
    BookReservedEvent.InputTuple,
    BookReservedEvent.OutputTuple,
    BookReservedEvent.OutputObject
  >;
  getEvent(
    key: "BookReturned"
  ): TypedContractEvent<
    BookReturnedEvent.InputTuple,
    BookReturnedEvent.OutputTuple,
    BookReturnedEvent.OutputObject
  >;
  getEvent(
    key: "LoanExtended"
  ): TypedContractEvent<
    LoanExtendedEvent.InputTuple,
    LoanExtendedEvent.OutputTuple,
    LoanExtendedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PenaltyWithdrawn"
  ): TypedContractEvent<
    PenaltyWithdrawnEvent.InputTuple,
    PenaltyWithdrawnEvent.OutputTuple,
    PenaltyWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BookAvailableForReservation(uint256,address)": TypedContractEvent<
      BookAvailableForReservationEvent.InputTuple,
      BookAvailableForReservationEvent.OutputTuple,
      BookAvailableForReservationEvent.OutputObject
    >;
    BookAvailableForReservation: TypedContractEvent<
      BookAvailableForReservationEvent.InputTuple,
      BookAvailableForReservationEvent.OutputTuple,
      BookAvailableForReservationEvent.OutputObject
    >;

    "BookBorrowed(address,uint256,uint256,uint256)": TypedContractEvent<
      BookBorrowedEvent.InputTuple,
      BookBorrowedEvent.OutputTuple,
      BookBorrowedEvent.OutputObject
    >;
    BookBorrowed: TypedContractEvent<
      BookBorrowedEvent.InputTuple,
      BookBorrowedEvent.OutputTuple,
      BookBorrowedEvent.OutputObject
    >;

    "BookInfoUpdated(uint256,string,string)": TypedContractEvent<
      BookInfoUpdatedEvent.InputTuple,
      BookInfoUpdatedEvent.OutputTuple,
      BookInfoUpdatedEvent.OutputObject
    >;
    BookInfoUpdated: TypedContractEvent<
      BookInfoUpdatedEvent.InputTuple,
      BookInfoUpdatedEvent.OutputTuple,
      BookInfoUpdatedEvent.OutputObject
    >;

    "BookReserved(uint256,address)": TypedContractEvent<
      BookReservedEvent.InputTuple,
      BookReservedEvent.OutputTuple,
      BookReservedEvent.OutputObject
    >;
    BookReserved: TypedContractEvent<
      BookReservedEvent.InputTuple,
      BookReservedEvent.OutputTuple,
      BookReservedEvent.OutputObject
    >;

    "BookReturned(address,uint256,uint256,int256,string)": TypedContractEvent<
      BookReturnedEvent.InputTuple,
      BookReturnedEvent.OutputTuple,
      BookReturnedEvent.OutputObject
    >;
    BookReturned: TypedContractEvent<
      BookReturnedEvent.InputTuple,
      BookReturnedEvent.OutputTuple,
      BookReturnedEvent.OutputObject
    >;

    "LoanExtended(uint256,address,uint256)": TypedContractEvent<
      LoanExtendedEvent.InputTuple,
      LoanExtendedEvent.OutputTuple,
      LoanExtendedEvent.OutputObject
    >;
    LoanExtended: TypedContractEvent<
      LoanExtendedEvent.InputTuple,
      LoanExtendedEvent.OutputTuple,
      LoanExtendedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PenaltyWithdrawn(address,uint256)": TypedContractEvent<
      PenaltyWithdrawnEvent.InputTuple,
      PenaltyWithdrawnEvent.OutputTuple,
      PenaltyWithdrawnEvent.OutputObject
    >;
    PenaltyWithdrawn: TypedContractEvent<
      PenaltyWithdrawnEvent.InputTuple,
      PenaltyWithdrawnEvent.OutputTuple,
      PenaltyWithdrawnEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
