/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface UserCartInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addToCart"
      | "addedAt"
      | "checkInCart"
      | "clearCart"
      | "getCart"
      | "getCartCount"
      | "getCartWithMetadata"
      | "getMyCart"
      | "getMyCartCount"
      | "isInCart"
      | "removeAfterBorrow"
      | "removeFromCart"
      | "totalCartItems"
      | "userCarts"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CartCleared" | "ItemAdded" | "ItemRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addToCart",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addedAt",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkInCart",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "clearCart", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCart",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCartCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCartWithMetadata",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getMyCart", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMyCartCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isInCart",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAfterBorrow",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromCart",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCartItems",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userCarts",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addToCart", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addedAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkInCart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "clearCart", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCart", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCartCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCartWithMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMyCart", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMyCartCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isInCart", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAfterBorrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromCart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCartItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userCarts", data: BytesLike): Result;
}

export namespace CartClearedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ItemAddedEvent {
  export type InputTuple = [
    user: AddressLike,
    bookId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, bookId: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    bookId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ItemRemovedEvent {
  export type InputTuple = [
    user: AddressLike,
    bookId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, bookId: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    bookId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UserCart extends BaseContract {
  connect(runner?: ContractRunner | null): UserCart;
  waitForDeployment(): Promise<this>;

  interface: UserCartInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addToCart: TypedContractMethod<[bookId: BigNumberish], [void], "nonpayable">;

  addedAt: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  checkInCart: TypedContractMethod<
    [user: AddressLike, bookId: BigNumberish],
    [boolean],
    "view"
  >;

  clearCart: TypedContractMethod<[], [void], "nonpayable">;

  getCart: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  getCartCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getCartWithMetadata: TypedContractMethod<
    [user: AddressLike],
    [[bigint[], bigint[]] & { bookIds: bigint[]; timestamps: bigint[] }],
    "view"
  >;

  getMyCart: TypedContractMethod<[], [bigint[]], "view">;

  getMyCartCount: TypedContractMethod<[], [bigint], "view">;

  isInCart: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  removeAfterBorrow: TypedContractMethod<
    [user: AddressLike, bookId: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeFromCart: TypedContractMethod<
    [bookId: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalCartItems: TypedContractMethod<[], [bigint], "view">;

  userCarts: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addToCart"
  ): TypedContractMethod<[bookId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addedAt"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkInCart"
  ): TypedContractMethod<
    [user: AddressLike, bookId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "clearCart"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCart"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getCartCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCartWithMetadata"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint[], bigint[]] & { bookIds: bigint[]; timestamps: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMyCart"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getMyCartCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isInCart"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeAfterBorrow"
  ): TypedContractMethod<
    [user: AddressLike, bookId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeFromCart"
  ): TypedContractMethod<[bookId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalCartItems"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "userCarts"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "CartCleared"
  ): TypedContractEvent<
    CartClearedEvent.InputTuple,
    CartClearedEvent.OutputTuple,
    CartClearedEvent.OutputObject
  >;
  getEvent(
    key: "ItemAdded"
  ): TypedContractEvent<
    ItemAddedEvent.InputTuple,
    ItemAddedEvent.OutputTuple,
    ItemAddedEvent.OutputObject
  >;
  getEvent(
    key: "ItemRemoved"
  ): TypedContractEvent<
    ItemRemovedEvent.InputTuple,
    ItemRemovedEvent.OutputTuple,
    ItemRemovedEvent.OutputObject
  >;

  filters: {
    "CartCleared(address,uint256)": TypedContractEvent<
      CartClearedEvent.InputTuple,
      CartClearedEvent.OutputTuple,
      CartClearedEvent.OutputObject
    >;
    CartCleared: TypedContractEvent<
      CartClearedEvent.InputTuple,
      CartClearedEvent.OutputTuple,
      CartClearedEvent.OutputObject
    >;

    "ItemAdded(address,uint256,uint256)": TypedContractEvent<
      ItemAddedEvent.InputTuple,
      ItemAddedEvent.OutputTuple,
      ItemAddedEvent.OutputObject
    >;
    ItemAdded: TypedContractEvent<
      ItemAddedEvent.InputTuple,
      ItemAddedEvent.OutputTuple,
      ItemAddedEvent.OutputObject
    >;

    "ItemRemoved(address,uint256,uint256)": TypedContractEvent<
      ItemRemovedEvent.InputTuple,
      ItemRemovedEvent.OutputTuple,
      ItemRemovedEvent.OutputObject
    >;
    ItemRemoved: TypedContractEvent<
      ItemRemovedEvent.InputTuple,
      ItemRemovedEvent.OutputTuple,
      ItemRemovedEvent.OutputObject
    >;
  };
}
