/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface LibraryCoreMinimalInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEPOSIT_AMOUNT"
      | "addBook"
      | "bookNFT"
      | "borrowBook"
      | "getLoanInfo"
      | "loanInfos"
      | "returnBook"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BookBorrowed" | "BookReturned"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEPOSIT_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addBook",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "bookNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "borrowBook",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "loanInfos",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "returnBook",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEPOSIT_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addBook", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bookNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "borrowBook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLoanInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loanInfos", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "returnBook", data: BytesLike): Result;
}

export namespace BookBorrowedEvent {
  export type InputTuple = [
    bookId: BigNumberish,
    borrower: AddressLike,
    deposit: BigNumberish
  ];
  export type OutputTuple = [bookId: bigint, borrower: string, deposit: bigint];
  export interface OutputObject {
    bookId: bigint;
    borrower: string;
    deposit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookReturnedEvent {
  export type InputTuple = [bookId: BigNumberish, borrower: AddressLike];
  export type OutputTuple = [bookId: bigint, borrower: string];
  export interface OutputObject {
    bookId: bigint;
    borrower: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LibraryCoreMinimal extends BaseContract {
  connect(runner?: ContractRunner | null): LibraryCoreMinimal;
  waitForDeployment(): Promise<this>;

  interface: LibraryCoreMinimalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEPOSIT_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  addBook: TypedContractMethod<
    [name: string, author: string],
    [bigint],
    "nonpayable"
  >;

  bookNFT: TypedContractMethod<[], [string], "view">;

  borrowBook: TypedContractMethod<[bookId: BigNumberish], [void], "payable">;

  getLoanInfo: TypedContractMethod<
    [bookId: BigNumberish],
    [
      [string, bigint, bigint] & {
        borrower: string;
        borrowTime: bigint;
        deposit: bigint;
      }
    ],
    "view"
  >;

  loanInfos: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        borrower: string;
        borrowTime: bigint;
        deposit: bigint;
      }
    ],
    "view"
  >;

  returnBook: TypedContractMethod<[bookId: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEPOSIT_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addBook"
  ): TypedContractMethod<
    [name: string, author: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bookNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "borrowBook"
  ): TypedContractMethod<[bookId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getLoanInfo"
  ): TypedContractMethod<
    [bookId: BigNumberish],
    [
      [string, bigint, bigint] & {
        borrower: string;
        borrowTime: bigint;
        deposit: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "loanInfos"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        borrower: string;
        borrowTime: bigint;
        deposit: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "returnBook"
  ): TypedContractMethod<[bookId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BookBorrowed"
  ): TypedContractEvent<
    BookBorrowedEvent.InputTuple,
    BookBorrowedEvent.OutputTuple,
    BookBorrowedEvent.OutputObject
  >;
  getEvent(
    key: "BookReturned"
  ): TypedContractEvent<
    BookReturnedEvent.InputTuple,
    BookReturnedEvent.OutputTuple,
    BookReturnedEvent.OutputObject
  >;

  filters: {
    "BookBorrowed(uint256,address,uint256)": TypedContractEvent<
      BookBorrowedEvent.InputTuple,
      BookBorrowedEvent.OutputTuple,
      BookBorrowedEvent.OutputObject
    >;
    BookBorrowed: TypedContractEvent<
      BookBorrowedEvent.InputTuple,
      BookBorrowedEvent.OutputTuple,
      BookBorrowedEvent.OutputObject
    >;

    "BookReturned(uint256,address)": TypedContractEvent<
      BookReturnedEvent.InputTuple,
      BookReturnedEvent.OutputTuple,
      BookReturnedEvent.OutputObject
    >;
    BookReturned: TypedContractEvent<
      BookReturnedEvent.InputTuple,
      BookReturnedEvent.OutputTuple,
      BookReturnedEvent.OutputObject
    >;
  };
}
