/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface BookNFTMinimalInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addBook"
      | "books"
      | "getBook"
      | "getBookStatus"
      | "libraryCore"
      | "nextBookId"
      | "setBookStatus"
      | "setLibraryCore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BookAdded" | "BookStatusChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addBook",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "books", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getBook",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBookStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "libraryCore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextBookId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBookStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setLibraryCore",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addBook", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "books", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBookStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "libraryCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextBookId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBookStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLibraryCore",
    data: BytesLike
  ): Result;
}

export namespace BookAddedEvent {
  export type InputTuple = [bookId: BigNumberish, name: string, author: string];
  export type OutputTuple = [bookId: bigint, name: string, author: string];
  export interface OutputObject {
    bookId: bigint;
    name: string;
    author: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookStatusChangedEvent {
  export type InputTuple = [bookId: BigNumberish, status: BigNumberish];
  export type OutputTuple = [bookId: bigint, status: bigint];
  export interface OutputObject {
    bookId: bigint;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BookNFTMinimal extends BaseContract {
  connect(runner?: ContractRunner | null): BookNFTMinimal;
  waitForDeployment(): Promise<this>;

  interface: BookNFTMinimalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addBook: TypedContractMethod<
    [name: string, author: string],
    [bigint],
    "nonpayable"
  >;

  books: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint] & {
        name: string;
        author: string;
        status: bigint;
      }
    ],
    "view"
  >;

  getBook: TypedContractMethod<
    [bookId: BigNumberish],
    [
      [string, string, bigint] & {
        name: string;
        author: string;
        status: bigint;
      }
    ],
    "view"
  >;

  getBookStatus: TypedContractMethod<[bookId: BigNumberish], [bigint], "view">;

  libraryCore: TypedContractMethod<[], [string], "view">;

  nextBookId: TypedContractMethod<[], [bigint], "view">;

  setBookStatus: TypedContractMethod<
    [bookId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  setLibraryCore: TypedContractMethod<
    [_libraryCore: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addBook"
  ): TypedContractMethod<
    [name: string, author: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "books"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint] & {
        name: string;
        author: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBook"
  ): TypedContractMethod<
    [bookId: BigNumberish],
    [
      [string, string, bigint] & {
        name: string;
        author: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBookStatus"
  ): TypedContractMethod<[bookId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "libraryCore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextBookId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setBookStatus"
  ): TypedContractMethod<
    [bookId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setLibraryCore"
  ): TypedContractMethod<[_libraryCore: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BookAdded"
  ): TypedContractEvent<
    BookAddedEvent.InputTuple,
    BookAddedEvent.OutputTuple,
    BookAddedEvent.OutputObject
  >;
  getEvent(
    key: "BookStatusChanged"
  ): TypedContractEvent<
    BookStatusChangedEvent.InputTuple,
    BookStatusChangedEvent.OutputTuple,
    BookStatusChangedEvent.OutputObject
  >;

  filters: {
    "BookAdded(uint256,string,string)": TypedContractEvent<
      BookAddedEvent.InputTuple,
      BookAddedEvent.OutputTuple,
      BookAddedEvent.OutputObject
    >;
    BookAdded: TypedContractEvent<
      BookAddedEvent.InputTuple,
      BookAddedEvent.OutputTuple,
      BookAddedEvent.OutputObject
    >;

    "BookStatusChanged(uint256,uint8)": TypedContractEvent<
      BookStatusChangedEvent.InputTuple,
      BookStatusChangedEvent.OutputTuple,
      BookStatusChangedEvent.OutputObject
    >;
    BookStatusChanged: TypedContractEvent<
      BookStatusChangedEvent.InputTuple,
      BookStatusChangedEvent.OutputTuple,
      BookStatusChangedEvent.OutputObject
    >;
  };
}
